"""Write app/requirements.txt for Streamlit Community Cloud from uv.lock.

    uv run python tools/streamlit_requirements.py

Core dependencies + the `web` extra (Streamlit), pinned to the locked versions, with OpenCV
swapped for its headless build (no GUI libraries on the server). Re-run after updating deps.
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from deploy_space import ROOT, requirements  # noqa: E402

if __name__ == "__main__":
    text, _ = requirements("web")
    header = "# Generated by tools/streamlit_requirements.py from uv.lock - do not edit by hand\n"
    out = ROOT / "app" / "requirements.txt"
    out.write_text(header + text, encoding="utf-8")
    print(f"wrote {out} ({len(text.splitlines())} packages)")
